
title: My Resume
url: 'http://junlulocky.com'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Ting Deng
title: SOFTWARE ENGINEER
location: San Francisco, CA


## Social Profiles
facebook: https://www.facebook.com/meltingd
twitter: https://twitter.com/tingex
linkedin: https://www.linkedin.com/in/tingdeng/
github: https://github.com/viinasu
email: mailto:maiden.belize+hellotingdeng@gmail.com
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
